function DU = backupDU_eul(in1,in2)
%BACKUPDU_EUL
%    DU = BACKUPDU_EUL(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    30-Aug-2020 19:25:55

KdAtt1 = in2(4,:);
KpAtt1 = in2(3,:);
KpOmegaz1 = in2(5,:);
KpVz1 = in2(2,:);
KpVxy1 = in2(1,:);
eul1 = in1(4,:);
eul2 = in1(5,:);
eul3 = in1(6,:);
hoverT1 = in2(6,:);
v1 = in1(7,:);
v2 = in1(8,:);
t2 = cos(eul1);
t3 = cos(eul2);
t4 = cos(eul3);
t5 = sin(eul1);
t6 = sin(eul2);
t7 = sin(eul3);
t10 = -KdAtt1;
t11 = -KpAtt1;
t12 = -KpOmegaz1;
t13 = -KpVz1;
t8 = t4.*v1;
t9 = t4.*v2;
t14 = t7.*v1;
t15 = t7.*v2;
t16 = 1.0./t2;
t18 = 1.0./t3;
t20 = KpAtt1.*KpVxy1.*t4;
t21 = KpAtt1.*KpVxy1.*t7;
t23 = KpVxy1.*t4.*t11;
t24 = KpVxy1.*t7.*t11;
t17 = t16.^2;
t19 = t18.^2;
t22 = -t14;
t25 = t8+t15;
t27 = t20+t21;
t29 = t20+t24;
t30 = t21+t23;
t35 = t23+t24;
t26 = t9+t22;
t28 = KpAtt1.*KpVxy1.*t25;
t32 = KpVxy1.*t11.*t25;
t33 = hoverT1.*t5.*t17.*t18;
t34 = hoverT1.*t6.*t16.*t19;
t31 = KpAtt1.*KpVxy1.*t26;
t36 = KpAtt1+t33;
t37 = KpAtt1+t34;
t38 = KpVxy1.*t11.*t26;
t39 = t11+t33;
t40 = t11+t34;
DU = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t36,t36,t39,t39,t37,t40,t40,t37,t28+t31,t28+t38,t32+t38,t31+t32,t27,t30,t35,t29,t30,t35,t29,t27,t13,t13,t13,t13,KdAtt1,KdAtt1,t10,t10,KdAtt1,t10,t10,KdAtt1,KpOmegaz1,t12,KpOmegaz1,t12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[4,16]);
